/* Example driver program for aes128BlockEncrypt. */
/* Automatically generated by SBV. Edit as you see fit! */

#include <inttypes.h>
#include <stdint.h>
#include "aes128BlockEncrypt.h"

int main(void)
{
  const SWord32 pt[4] = {
      0x00112233UL, 0x44556677UL, 0x8899aabbUL, 0xccddeeffUL
  };
  
  const SWord32 key[4] = {
      0x00010203UL, 0x04050607UL, 0x08090a0bUL, 0x0c0d0e0fUL
  };
  
  SWord32 ct[4];
  
  aes128BlockEncrypt(pt, key, ct);
  
  return
         ct[0] == 0x69c4e0d8UL
      && ct[1] == 0x6a7b0430UL
      && ct[2] == 0xd8cdb780UL
      && ct[3] == 0x70b4c55aUL;
}
