/* Example driver program for aes128BlockEncrypt. */
/* Automatically generated by SBV. Edit as you see fit! */

#include <inttypes.h>
#include <stdint.h>
#include <stdio.h>
#include "aes128BlockEncrypt.h"

int main(void)
{
  const SWord32 pt[4] = {
      0x00112233UL, 0x44556677UL, 0x8899aabbUL, 0xccddeeffUL
  };
  
  printf("Contents of input array pt:\n");
  int pt_ctr;
  for(pt_ctr = 0;  pt_ctr < 4 ; ++pt_ctr)
    printf("  pt[%d] = 0x%08"PRIx32"UL\n", pt_ctr ,pt[pt_ctr]);
  
  const SWord32 key[4] = {
      0x00010203UL, 0x04050607UL, 0x08090a0bUL, 0x0c0d0e0fUL
  };
  
  printf("Contents of input array key:\n");
  int key_ctr;
  for(key_ctr = 0;  key_ctr < 4 ; ++key_ctr)
    printf("  key[%d] = 0x%08"PRIx32"UL\n", key_ctr ,key[key_ctr]);
  
  SWord32 ct[4];
  
  aes128BlockEncrypt(pt, key, ct);
  
  printf("aes128BlockEncrypt(pt, key, ct) ->\n");

  int ct_ctr;
  for(ct_ctr = 0;  ct_ctr < 4 ; ++ct_ctr)
    printf("  ct[%d] = 0x%08"PRIx32"UL\n", ct_ctr ,ct[ct_ctr]);

  if (   ct[0] == 0x69c4e0d8UL
      && ct[1] == 0x6a7b0430UL
      && ct[2] == 0xd8cdb780UL
      && ct[3] == 0x70b4c55aUL)
      printf("Obtained expected result.");
  else
      printf("Failed to obtain expected result.");
  
  return 0;
}
